version: "3"
services:
  client:
    image: "vladismarkin/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "vladismarkin/multi-server"
    mem_limit: 128m
    hostname: api
  nginx:
    image: "vladismarkin/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
